# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseExample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseExample

  target 'FirebaseExampleTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Firebase'
  end

end
